## Deliverable 3. Create a Travel Itinerary Map.

In [4]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [6]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()


City_ID             City Country  Max Temp Current Description      Lat  \
0        0  Bambous Virieux      MU     73.22          light rain -20.3428   
1        1             Yako      BF     73.60    scattered clouds  12.9667   
2        2             Hilo      US     78.53       moderate rain  19.7297   
3        7          Biltine      TD     78.40     overcast clouds  14.5333   
4       10          Rikitea      PF     73.40          light rain -23.1203   

        Lng                      Hotel Name  
0   57.7575                  Casa Tia Villa  
1   -2.2667                          CADAAY  
2 -155.0900             Hilo Hawaiian Hotel  
3   20.9167  Hôtel Trois Étoiles de Biltine  
4 -134.9692                 People ThankYou

In [7]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather with Max Temp</dt><dd>{Current Description} & {Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
vacation_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [8]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=vacation_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [23]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"] == "Fortuna")]
vacation_end = vacation_df.loc[(vacation_df["City"] == "Fortuna")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] == "Winnemucca")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] == "Pocatello")]
vacation_stop3 = vacation_df.loc[(vacation_df["City"] == "Pierre")]            
vacation_start

City_ID     City Country  Max Temp Current Description      Lat  \
114      321  Fortuna      US     70.41           clear sky  40.5982   

          Lng                  Hotel Name  
114 -124.1573  Super 8 by Wyndham Fortuna

In [24]:
vacation_stop1

City_ID        City Country  Max Temp Current Description     Lat  \
191      567  Winnemucca      US     75.11           clear sky  40.973   

          Lng          Hotel Name  
191 -117.7357  Winners Inn Casino

In [25]:
vacation_stop2

City_ID       City Country  Max Temp Current Description      Lat  \
155      464  Pocatello      US     75.11           clear sky  42.8713   

          Lng             Hotel Name  
155 -112.4455  Clarion Inn Pocatello

In [26]:
vacation_stop3

City_ID    City Country  Max Temp Current Description      Lat      Lng  \
201      597  Pierre      US     77.92           clear sky  44.3683 -100.351   

        Hotel Name  
201  Ramkota Hotel

In [27]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat","Lng"]].to_numpy()[0]  
end = vacation_end[["Lat","Lng"]].to_numpy()[0]
stop1 = vacation_stop1[["Lat","Lng"]].to_numpy()[0]
stop2 = vacation_stop2[["Lat","Lng"]].to_numpy()[0] 
stop3 = vacation_stop3[["Lat","Lng"]].to_numpy()[0] 
start

array([  40.5982, -124.1573])

In [28]:
stop1

array([  40.973 , -117.7357])

In [30]:
stop2

array([  42.8713, -112.4455])

In [31]:
stop3

array([  44.3683, -100.351 ])

In [32]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
Fortuna = start
Winnemucca = stop1
Pocatello = stop2
Pierre = stop3
Fortuna = end

fig = gmaps.figure()
bud_round_trip = gmaps.directions_layer(
    Fortuna, Fortuna, waypoints=[Winnemucca, Pocatello, Pierre],
    travel_mode='DRIVING')
fig.add_layer(bud_round_trip)
fig


Figure(layout=FigureLayout(height='420px'))

In [33]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID        City Country  Max Temp Current Description      Lat  \
0      321     Fortuna      US     70.41           clear sky  40.5982   
1      567  Winnemucca      US     75.11           clear sky  40.9730   
2      464   Pocatello      US     75.11           clear sky  42.8713   
3      597      Pierre      US     77.92           clear sky  44.3683   

        Lng                  Hotel Name  
0 -124.1573  Super 8 by Wyndham Fortuna  
1 -117.7357          Winners Inn Casino  
2 -112.4455       Clarion Inn Pocatello  
3 -100.3510               Ramkota Hotel

In [34]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather with Max Temp</dt><dd>{Current Description} & {Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [35]:
# 11a. Add a marker layer for each city to the map.
locations = itinerary_df[["Lat", "Lng"]]
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))